### ISSUE TITLE
Path metrics generation don't work!

### ISSUE THREAD

**Issue by yuqikong** [akanametov/pathgan#1]
after run train.py, get_logs.py don't work! help!

**Comment by chengcongcong222** [comment]
> 运行 train.py 后，get_logs.py 不起作用！帮助！

Have you solved this problem? plz

**Comment by chengcongcong222** [comment]
> Hello, I am a Master's student from China and I am very interested in your project and I have benefited a lot from this project. 
> Now I have a problem, I don't know how to run the test set and how to run the file get_logs.py.
> I hope you have time to guide me, thank you very much.

**Comment by ayeffkay** [comment]
> > Hello, I am a Master's student from China and I am very interested in your project and I have benefited a lot from this project.
> > Now I have a problem, I don't know how to run the test set and how to run the file get_logs.py.
> > I hope you have time to guide me, thank you very much.

Hello! As you, we are Master's students from Russia. This was our course project on path planning. We haven't plans to maintain this project, so you can use this code at yours own risk. But it worked last year :) Now we don't have ability to help you as we haven't seen this code since last year and different parts of code was written by different members of our team (and it takes time to remember own code and someone's else code). We apologize for the inconvenience.

**Comment by chengcongcong222** [comment]
Still, thank you very much. I also appreciate your prompt response.
BTW, the paper linked to this project is a paper from China, is it convenient to ask if you are a team? Would I be able to learn from the author of that paper?
I am sorry to bother you! I hope you will forgive me!

**Comment by ayeffkay** [comment]
> Would I be able to learn from the author of that paper?

We have no relationship to the authors of this paper. We just found it and implemented proposed approach, as we understood it :)

**Comment by chengcongcong222** [comment]
Thank you very much for your enthusiastic reply. I am a new graduate student and this program has taught me a lot and I will continue to work hard to learn from you seniors.
